// Code generated by goctl. DO NOT EDIT.
package types

type CurdCreateRequest struct {
	ModelName  string `json:"model_name"`
	OnlyGenApi bool   `json:"only_gen_api"`
}

type Empty struct {
}

type HelloWorldResponse struct {
	Data string `json:"data"`
}

type TdFirmCreateRequest struct {
	FirmName  string `json:"firm_name"`
	FirmAlias string `json:"firm_alias"`
	FirmCode  string `json:"firm_code"`
	FirmDesc  string `json:"firm_desc"`
}

type TdFirmCreateResponse struct {
	FirmId    string `json:"firm_id"`
	FirmName  string `json:"firm_name"`
	FirmAlias string `json:"firm_alias"`
	FirmCode  string `json:"firm_code"`
	FirmDesc  string `json:"firm_desc"`
}

type TdFirmDeleteRequest struct {
	FirmId string `form:"firm_id"`
}

type TdFirmDeleteResponse struct {
	FirmId string `json:"firm_id"`
}

type TdFirmDetailRequest struct {
	FirmId string `form:"firm_id"`
}

type TdFirmDetailResponse struct {
	FirmId    string `json:"firm_id"`
	FirmName  string `json:"firm_name"`
	FirmAlias string `json:"firm_alias"`
	FirmCode  string `json:"firm_code"`
	FirmDesc  string `json:"firm_desc"`
}

type TdFirmListRequest struct {
	PageSize  int     `form:"page_size"`
	PageNum   int     `form:"page_num"`
	FirmName  *string `form:"firm_name,optional"`
	FirmAlias *string `form:"firm_alias,optional"`
	FirmCode  *string `form:"firm_code,optional"`
	FirmDesc  *string `form:"firm_desc,optional"`
}

type TdFirmListResponse struct {
	List  []*TdFirmUpdateResponse `json:"list"`
	Total int64                   `json:"total"`
}

type TdFirmUpdateRequest struct {
	FirmId    string `json:"firm_id"`
	FirmName  string `json:"firm_name"`
	FirmAlias string `json:"firm_alias"`
	FirmCode  string `json:"firm_code"`
	FirmDesc  string `json:"firm_desc"`
}

type TdFirmUpdateResponse struct {
	FirmId    string `json:"firm_id"`
	FirmName  string `json:"firm_name"`
	FirmAlias string `json:"firm_alias"`
	FirmCode  string `json:"firm_code"`
	FirmDesc  string `json:"firm_desc"`
}
