// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	curd "github.com/zyw0605688/gozero-curd-vue/service/public/internal/handler/curd"
	"github.com/zyw0605688/gozero-curd-vue/service/public/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: curd.HelloWorldHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/curd",
				Handler: curd.CurdCreateHandler(serverCtx),
			},
		},
	)

}
